// @generated automatically by Diesel CLI.

diesel::table! {
    block_stats (height) {
        height -> BigInt,
        date -> Date,
        version -> Integer,
        nonce -> Integer,
        bits -> Integer,
        size -> BigInt,
        stripped_size -> BigInt,
        vsize -> BigInt,
        weight -> BigInt,
        empty -> Bool,
        coinbase_output_amount -> BigInt,
        coinbase_weight -> BigInt,
        transactions -> Integer,
        payments -> Integer,
        payments_segwit_spending_tx -> Integer,
        payments_taproot_spending_tx -> Integer,
        payments_signaling_explicit_rbf -> Integer,
        inputs -> Integer,
        outputs -> Integer,
        pool_id -> Integer,
        difficulty -> BigInt,
        log2_work -> Float,
    }
}

diesel::table! {
    feerate_stats (height) {
        height -> BigInt,
        date -> Date,
        fee_min -> BigInt,
        fee_5th_percentile -> BigInt,
        fee_10th_percentile -> BigInt,
        fee_25th_percentile -> BigInt,
        fee_35th_percentile -> BigInt,
        fee_50th_percentile -> BigInt,
        fee_65th_percentile -> BigInt,
        fee_75th_percentile -> BigInt,
        fee_90th_percentile -> BigInt,
        fee_95th_percentile -> BigInt,
        fee_max -> BigInt,
        fee_sum -> BigInt,
        fee_avg -> Float,
        size_min -> Integer,
        size_5th_percentile -> Integer,
        size_10th_percentile -> Integer,
        size_25th_percentile -> Integer,
        size_35th_percentile -> Integer,
        size_50th_percentile -> Integer,
        size_65th_percentile -> Integer,
        size_75th_percentile -> Integer,
        size_90th_percentile -> Integer,
        size_95th_percentile -> Integer,
        size_max -> Integer,
        size_avg -> Float,
        size_sum -> BigInt,
        feerate_min -> Float,
        feerate_5th_percentile -> Float,
        feerate_10th_percentile -> Float,
        feerate_25th_percentile -> Float,
        feerate_35th_percentile -> Float,
        feerate_50th_percentile -> Float,
        feerate_65th_percentile -> Float,
        feerate_75th_percentile -> Float,
        feerate_90th_percentile -> Float,
        feerate_95th_percentile -> Float,
        feerate_max -> Float,
        feerate_avg -> Float,
        feerate_package_min -> Float,
        feerate_package_5th_percentile -> Float,
        feerate_package_10th_percentile -> Float,
        feerate_package_25th_percentile -> Float,
        feerate_package_35th_percentile -> Float,
        feerate_package_50th_percentile -> Float,
        feerate_package_65th_percentile -> Float,
        feerate_package_75th_percentile -> Float,
        feerate_package_90th_percentile -> Float,
        feerate_package_95th_percentile -> Float,
        feerate_package_max -> Float,
        feerate_package_avg -> Float,
    }
}

diesel::table! {
    input_stats (height) {
        height -> BigInt,
        date -> Date,
        inputs_spending_legacy -> Integer,
        inputs_spending_segwit -> Integer,
        inputs_spending_taproot -> Integer,
        inputs_spending_nested_segwit -> Integer,
        inputs_spending_native_segwit -> Integer,
        inputs_spending_multisig -> Integer,
        inputs_spending_p2ms_multisig -> Integer,
        inputs_spending_p2sh_multisig -> Integer,
        inputs_spending_nested_p2wsh_multisig -> Integer,
        inputs_spending_p2wsh_multisig -> Integer,
        inputs_p2pk -> Integer,
        inputs_p2pkh -> Integer,
        inputs_nested_p2wpkh -> Integer,
        inputs_p2wpkh -> Integer,
        inputs_p2ms -> Integer,
        inputs_p2sh -> Integer,
        inputs_nested_p2wsh -> Integer,
        inputs_p2wsh -> Integer,
        inputs_coinbase -> Integer,
        inputs_witness_coinbase -> Integer,
        inputs_p2tr_keypath -> Integer,
        inputs_p2tr_scriptpath -> Integer,
        inputs_unknown -> Integer,
        inputs_spend_in_same_block -> Integer,
        inputs_p2a -> Integer,
        inputs_p2a_dust -> Integer,
    }
}

diesel::table! {
    output_stats (height) {
        height -> BigInt,
        date -> Date,
        outputs_p2pk -> Integer,
        outputs_p2pkh -> Integer,
        outputs_p2wpkh -> Integer,
        outputs_p2ms -> Integer,
        outputs_p2sh -> Integer,
        outputs_p2wsh -> Integer,
        outputs_opreturn -> Integer,
        outputs_p2tr -> Integer,
        outputs_unknown -> Integer,
        outputs_p2pk_amount -> BigInt,
        outputs_p2pkh_amount -> BigInt,
        outputs_p2wpkh_amount -> BigInt,
        outputs_p2ms_amount -> BigInt,
        outputs_p2sh_amount -> BigInt,
        outputs_p2wsh_amount -> BigInt,
        outputs_p2tr_amount -> BigInt,
        outputs_opreturn_amount -> BigInt,
        outputs_unknown_amount -> BigInt,
        outputs_p2a -> Integer,
        outputs_p2a_amount -> BigInt,
        outputs_p2a_dust -> Integer,
        outputs_opreturn_omnilayer -> Integer,
        outputs_opreturn_stacks_block_commit -> Integer,
        outputs_opreturn_bip47_payment_code -> Integer,
        outputs_opreturn_coinbase_rsk -> Integer,
        outputs_opreturn_coinbase_coredao -> Integer,
        outputs_opreturn_coinbase_exsat -> Integer,
        outputs_opreturn_coinbase_hathor -> Integer,
        outputs_opreturn_coinbase_witness_commitment -> Integer,
        outputs_opreturn_runestone -> Integer,
    }
}

diesel::table! {
    script_stats (height) {
        height -> BigInt,
        date -> Date,
        pubkeys -> Integer,
        pubkeys_compressed -> Integer,
        pubkeys_uncompressed -> Integer,
        pubkeys_compressed_inputs -> Integer,
        pubkeys_uncompressed_inputs -> Integer,
        pubkeys_compressed_outputs -> Integer,
        pubkeys_uncompressed_outputs -> Integer,
        sigs_schnorr -> Integer,
        sigs_ecdsa -> Integer,
        sigs_ecdsa_not_strict_der -> Integer,
        sigs_ecdsa_strict_der -> Integer,
        sigs_ecdsa_length_less_70byte -> Integer,
        sigs_ecdsa_length_70byte -> Integer,
        sigs_ecdsa_length_71byte -> Integer,
        sigs_ecdsa_length_72byte -> Integer,
        sigs_ecdsa_length_73byte -> Integer,
        sigs_ecdsa_length_74byte -> Integer,
        sigs_ecdsa_length_75byte_or_more -> Integer,
        sigs_ecdsa_low_r -> Integer,
        sigs_ecdsa_high_r -> Integer,
        sigs_ecdsa_low_s -> Integer,
        sigs_ecdsa_high_s -> Integer,
        sigs_ecdsa_high_rs -> Integer,
        sigs_ecdsa_low_rs -> Integer,
        sigs_ecdsa_low_r_high_s -> Integer,
        sigs_ecdsa_high_r_low_s -> Integer,
        sigs_sighashes -> Integer,
        sigs_sighash_all -> Integer,
        sigs_sighash_none -> Integer,
        sigs_sighash_single -> Integer,
        sigs_sighash_all_acp -> Integer,
        sigs_sighash_none_acp -> Integer,
        sigs_sighash_single_acp -> Integer,
    }
}

diesel::table! {
    tx_stats (height) {
        height -> BigInt,
        date -> Date,
        tx_version_1 -> Integer,
        tx_version_2 -> Integer,
        tx_version_3 -> Integer,
        tx_version_unknown -> Integer,
        tx_output_amount -> BigInt,
        tx_spending_segwit -> Integer,
        tx_spending_only_segwit -> Integer,
        tx_spending_only_legacy -> Integer,
        tx_spending_only_taproot -> Integer,
        tx_spending_segwit_and_legacy -> Integer,
        tx_spending_nested_segwit -> Integer,
        tx_spending_native_segwit -> Integer,
        tx_spending_taproot -> Integer,
        tx_bip69_compliant -> Integer,
        tx_signaling_explicit_rbf -> Integer,
        tx_1_input -> Integer,
        tx_1_output -> Integer,
        tx_1_input_1_output -> Integer,
        tx_1_input_2_output -> Integer,
        tx_spending_newly_created_utxos -> Integer,
        tx_timelock_height -> Integer,
        tx_timelock_timestamp -> Integer,
        tx_timelock_not_enforced -> Integer,
        tx_timelock_too_high -> Integer,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    block_stats,
    feerate_stats,
    input_stats,
    output_stats,
    script_stats,
    tx_stats,
);
